// Generated by CoffeeScript 1.10.0

/*

Restructures data after it was read into an array from a file exported from the worldbank data bank
see:  http://databank.worldbank.org/data/reports.aspx?source=world-development-indicators&preview=on#

Limitations:
Currently only supports data with one "Series" (Adjusted Income, GDP, etc..)
 */

(function() {
  window.worldBankDataParser = {
    yearRange: function(importedWorldBankData) {
      var i, key, len, matches, range, ref;
      range = {
        startDate: null,
        endDate: null
      };
      ref = Object.keys(importedWorldBankData[0]);
      for (i = 0, len = ref.length; i < len; i++) {
        key = ref[i];
        matches = key.match(/^(\d{4})/);
        if (matches) {
          if (range.startDate === null) {
            range.startDate = matches[0];
          }
          range.endDate = matches[0];
        }
      }
      return range;
    },
    countryData: function(importedWorldBankData) {
      return importedWorldBankData.filter(function(countryData) {
        return countryData['Country Code'].length > 0;
      }).map(function(countryData) {
        return {
          name: countryData['Country Code'],
          values: Object.keys(countryData).map(function(key) {
            var firstYear, matches, val;
            matches = key.match(/^(\d{4})/);
            if (matches) {
              if (!firstYear) {
                firstYear = matches[0];
              }
              val = countryData[key];
              if (val === '..') {
                return null;
              } else {
                return parseFloat(val);
              }
            }
          }).filter(function(val) {
            return val !== void 0;
          })
        };
      }).filter(function(country) {
        return country['values'] !== void 0;
      });
    }
  };

}).call(this);

//# sourceMappingURL=worldbank_data_importer.js.map
